version: '3.8'

services:

  portfolio-front:
    container_name: portfolio-FRONT
    build:
      dockerfile: Dockerfile
      context: p_front
      target: ${TARGET}
    volumes:
      - ./p_front:/app
      - /app/node_modules/
    ports:
      - ${PORT_ANGULAR}:4200